spring.application.name=payment-gateway-configaration

#PORT Configuration
server.port=8001

#Swagger configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.defaultModelsExpandDepth=1
springdoc.swagger-ui.docExpansion=none
springdoc.swagger-ui.operationsSorter=alpha

#Api keys
adyen.api.key=AQEvhmfxK4LGbRNDw0m/n3Q5qf3VfKh+LJBJV3BY0iHzyp79nlTRS0WfNNR6AZcrUasQwV1bDb7kfNy1WIxIIkxgBw==-PgMyhRwzBKY/BpOmnl/wdQ51xvSuOJQpovmko11pvPQ=-i1iW*a::ZAk]Vv&d4]H
adyen.merchant.account=TCSAccount984ECOM
adyen.client.env=test
adyen.checkout.url=https://checkout-test.adyen.com/v71

#Card Payment URI
adyan.card.uri=https://pal-test.adyen.com/pal/servlet/Payment/v68/authorise